---
- name: Install system packages
  apt:
    name: "{{ system_packages }}"
    state: present
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: Create application user and group
  user:
    name: "{{ nasapuff_app_user }}"
    group: "{{ nasapuff_app_group }}"
    system: yes
    shell: /bin/bash
    home: "{{ nasapuff_base_dir }}"
    create_home: yes

- name: Create application directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ nasapuff_app_user }}"
    group: "{{ nasapuff_app_group }}"
    mode: '0755'
  loop:
    - "{{ nasapuff_base_dir }}"
    - "{{ nasapuff_flask_dir }}"
    - "{{ nasapuff_log_dir }}"
    - "{{ nasapuff_backup_dir }}"
    - "{{ nasapuff_flask_dir }}/templates"
    - "{{ nasapuff_flask_dir }}/public"
    - "{{ nasapuff_flask_dir }}/public/css"

- name: Set up logrotate for application logs
  template:
    src: nasapuff-logrotate.j2
    dest: /etc/logrotate.d/nasapuff
    owner: root
    group: root
    mode: '0644' 