all:
  children:
    nasapuff_servers:
      hosts:
        nasapuff-host77:
          ansible_host: host77.nird.club
          ansible_user: ansible
          ansible_ssh_private_key_file: ~/.ssh/keys/nirdclub__id_ed25519
        nasapuff-host78:
          ansible_host: host78.nird.club
          ansible_user: ansible
          ansible_ssh_private_key_file: ~/.ssh/keys/nirdclub__id_ed25519
      vars:
        nasapuff_domain: nasa.puhfph.cloud
        nasapuff_ssl_email: admin@nasa.puhfph.cloud
        nasapuff_app_port: 48080
        nasapuff_app_user: nasapuff
        nasapuff_app_group: nasapuff
        nasapuff_base_dir: /var/bertain-cdn/nasapuff
        nasapuff_flask_dir: "{{ nasapuff_base_dir }}/flask"
        nasapuff_venv_dir: "{{ nasapuff_flask_dir }}/venv-nasapuff"
        nasapuff_log_dir: /var/log/nasapuff
        nasapuff_backup_dir: /var/backups/nasapuff 